version: '3.8'


services:
  mysqldb:
    image: mysql:latest
    env_file: ./.env
    container_name: flutter-product-api-mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  
  migrate:
    build: .
    command: yarn db:migrate
    container_name: flutter-product-api-migrate
    image: flutter-product-api-migrate
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - DB_HOST=mysqldb
    depends_on:
      - mysqldb

  app:
    depends_on:
      - mysqldb
      - migrate
    build: .
    command: yarn start
    image: flutter-product-api-app
    container_name: flutter-product-api-app
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - NODE_ENV=production
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - DB_HOST=mysqldb
    stdin_open: true
    tty: true

volumes: 
  db: